import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { HeroComponent } from './components/hero';
import { IntroComponent } from './components/intro';
import { EventDetailsComponent } from './components/event-details';
import { LocationComponent } from './components/location';
import { GalleryComponent } from './components/gallery';
import { RsvpComponent } from './components/rsvp';
import { DressCodeComponent } from './components/dress-code';
import { CONTENT } from './website-content';
import { WelcomeOverlayComponent } from './components/welcome-overlay';
// import Swiper element registration function
import { register } from 'swiper/element/bundle';

// register Swiper custom elements
register();

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    RouterOutlet,
    HeroComponent,
    IntroComponent,
    EventDetailsComponent,
    LocationComponent,
    GalleryComponent,
    RsvpComponent,
    DressCodeComponent,
    WelcomeOverlayComponent
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <app-welcome-overlay 
      *ngIf="showWelcome" 
      [name]="content.baby.name" 
      (enter)="handleEnter()">
    </app-welcome-overlay>

    <div class="app-container" [class.hidden]="showWelcome">
      <!-- Floating Balloons Container -->
      <div class="balloons-container">
        <!-- Balloons are generated by logic below, or we can just use fixed ones -->
        <div class="balloon" *ngFor="let b of balloons" 
             [style.left.%]="b.left" 
             [style.animation-duration]="b.duration + 's'"
             [style.animation-delay]="b.delay + 's'"
             [style.background-color]="b.color">
        </div>
      </div>

      <!-- Sparkles/Particles -->
      <div class="sparkles-container">
         <div class="sparkle" *ngFor="let s of sparkles"
              [style.left.%]="s.left"
              [style.top.%]="s.top"
              [style.animation-delay]="s.delay + 's'"
              [style.animation-duration]="s.duration + 's'">
         </div>
      </div>

      <main>
        <app-hero></app-hero>
        <app-intro></app-intro>
        <app-event-details></app-event-details>
        <app-location></app-location>
        <app-gallery></app-gallery>
        <app-dress-code></app-dress-code>
        <app-rsvp id="rsvp"></app-rsvp>
      </main>

      <footer>
        <p>With Love, The Maquiling Family</p>
      </footer>
    </div>
  `,
  styles: []
})
export class App {
  content = CONTENT;
  showWelcome = true; // Gatekeeper logic

  balloons = Array.from({ length: 15 }).map(() => ({
    left: Math.random() * 100,
    duration: 15 + Math.random() * 15, // Slower: 15-30s
    delay: Math.random() * 20,
    color: this.getRandomColor()
  }));

  sparkles = Array.from({ length: 40 }).map(() => ({
    left: Math.random() * 100,
    top: Math.random() * -20, // Start slightly above
    delay: Math.random() * 5,
    duration: 3 + Math.random() * 5 // Random fall speed 3-8s
  }));

  handleEnter() {
    this.showWelcome = false;
  }

  getRandomColor() {
    const colors = ['#ff9a9e', '#fad0c4', '#a18cd1', '#fbc2eb'];
    return colors[Math.floor(Math.random() * colors.length)];
  }
}
