import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { IntroComponent } from './components/intro';
import { EventDetailsComponent } from './components/event-details';
import { LocationComponent } from './components/location';
import { GalleryComponent } from './components/gallery';
import { RsvpComponent } from './components/rsvp';
import { DressCodeComponent } from './components/dress-code';
import { CONTENT } from './website-content';
import { WelcomeOverlayComponent } from './components/welcome-overlay';
// import Swiper element registration function
import { register } from 'swiper/element/bundle';

// register Swiper custom elements
register();

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    RouterOutlet,
    IntroComponent,
    EventDetailsComponent,
    LocationComponent,
    GalleryComponent,
    RsvpComponent,
    DressCodeComponent,
    WelcomeOverlayComponent
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <app-welcome-overlay 
      *ngIf="showWelcome" 
      [name]="content.baby.name" 
      (enter)="handleEnter()">
    </app-welcome-overlay>

    <div class="app-container" [class.hidden]="showWelcome">
      <!-- Floating Balloons Container -->
      <div class="balloons-container">
        <!-- Balloons are generated by logic below, or we can just use fixed ones -->
        <div class="balloon" *ngFor="let b of balloons" 
             [style.left.%]="b.left" 
             [style.animation-duration]="b.duration + 's'"
             [style.animation-delay]="b.delay + 's'"
             [style.background-color]="b.color">
        </div>
      </div>

      <!-- Sparkles/Particles -->
      <div class="sparkles-container">
         <div class="sparkle" *ngFor="let s of sparkles"
              [style.left.%]="s.left"
              [style.top.%]="s.top"
              [style.animation-delay]="s.delay + 's'">
         </div>
      </div>

      <main>
        <app-intro></app-intro>
        <app-event-details></app-event-details>
        <app-location></app-location>
        <app-gallery></app-gallery>
        <app-dress-code></app-dress-code>
        <app-rsvp></app-rsvp>
      </main>

      <footer>
        <p>With Love, The Maquiling Family</p>
      </footer>
    </div>
  `,
  styles: [`
    :host {
      --color-primary: #ff9a9e;
      --color-accent: #fad0c4;
      --color-bg: #fff0f3; /* Soft Pink Background */
      --color-text: #555;
      --font-heading: 'Great Vibes', cursive;
      --font-body: 'Cormorant Garamond', serif;
      
      display: block;
      min-height: 100vh;
      color: var(--color-text);
      font-family: var(--font-body);
      background: linear-gradient(135deg, #fff0f3 0%, #e0f7fa 100%); /* Pink to Light Blue gradient */
      overflow-x: hidden;
    }

    .hidden {
      height: 100vh;
      overflow: hidden;
      filter: blur(10px);
    }

    /* Fixed Balloons & Sparkles */
    .balloons-container, .sparkles-container {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      pointer-events: none;
      z-index: 0;
      overflow: hidden;
    }

    .balloon {
      position: absolute;
      bottom: -100px; /* Start below screen */
      width: 40px;
      height: 55px; /* Slightly taller for oval shape */
      border-radius: 50% 50% 50% 50% / 40% 40% 60% 60%; /* Balloon shape */
      opacity: 0.6;
      animation: floatUp linear infinite; /* Removed rotation */
    }
    
    .balloon::before {
       /* String */
       content: '';
       position: absolute;
       bottom: -15px;
       left: 50%;
       width: 1px;
       height: 25px;
       background: rgba(0,0,0,0.1);
    }

    @keyframes floatUp {
      0% {
        transform: translateY(0) translateX(0);
        opacity: 0;
      }
      10% {
        opacity: 0.7;
      }
      50% {
        transform: translateY(-50vh) translateX(15px); /* Gentle sway right */
      }
      100% {
        transform: translateY(-120vh) translateX(-15px); /* Sway left and exit top */
        opacity: 0;
      }
    }

    /* ... Sparkles ... */
    .sparkle {
      position: absolute;
      width: 4px;
      height: 4px;
      background: white;
      border-radius: 50%;
      box-shadow: 0 0 5px 2px rgba(255, 255, 255, 0.8);
      animation: twinkle 3s infinite;
    }

    @keyframes twinkle {
       0%, 100% { opacity: 0; transform: scale(0.5); }
       50% { opacity: 1; transform: scale(1.2); }
    }

    /* ... Footer ... */
    footer {
      text-align: center;
      padding: 3rem;
      font-size: 0.9rem;
      opacity: 0.7;
      position: relative;
      z-index: 1;
    }
  `]
})
export class App {
  content = CONTENT;
  showWelcome = true; // Gatekeeper logic

  balloons = Array.from({ length: 15 }).map(() => ({
    left: Math.random() * 100,
    duration: 15 + Math.random() * 15, // Slower: 15-30s
    delay: Math.random() * 20,
    color: this.getRandomColor()
  }));

  sparkles = Array.from({ length: 30 }).map(() => ({
    left: Math.random() * 100,
    top: Math.random() * 100,
    delay: Math.random() * 3
  }));

  handleEnter() {
    this.showWelcome = false;
  }

  getRandomColor() {
    const colors = ['#ff9a9e', '#fad0c4', '#a18cd1', '#fbc2eb'];
    return colors[Math.floor(Math.random() * colors.length)];
  }
}
